vim.keymap.set("n", "<leader>o", function()
	require("oil").toggle_float()
end)
vim.keymap.set("n", "<leader>w", "<cmd>write<CR>", { desc = "Save File" })
vim.keymap.set("n", "<leader>n", ":cnext<CR>", {})
vim.keymap.set("n", "<leader>N", ":cprevious<CR>", {})
-- Diagnostics key mappings
vim.keymap.set("n", "<leader>d", vim.diagnostic.open_float, {})
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, {})
vim.keymap.set("n", "<leader>Q", vim.diagnostic.setqflist, {})
vim.keymap.set("n", "[d", function()
	vim.diagnostic.jump({ count = -1 })
end, {})
vim.keymap.set("n", "]d", function()
	vim.diagnostic.jump({ count = 1 })
end, {})
